#include "../fe.h"

void usage(void) {
    printf(
"\n"
"Welcome to FE V" VER ", a file-encryptor that can intercept disk IO.\n"
"Copyright (c) Karel Kubat 2015ff, all rights reserved.\n"
"Contact <karel@kubat.nl> for information. Distributed under GPLV3.\n"
"\n"
"Usage: fe [FLAGS]  --file FILE                # transcrypt FILE in place\n"
"   or: fe [FLAGS] [--target FILE ] CMD ARGS   # spawn command\n"
"   or: fe  -V                                 # show version ID\n"
"Supported flags are:\n"
" --help, -h, -?    This help\n"
" --verbose, -v     Increases verbosity\n"
" --stderr, -s      Sends verbose messages to stderr instead of to syslog\n"
" --environment,    Uses the environment to pass context to next programs,\n"
"  -e               default is to use shared memory\n"
" --ignore-uncaught Ignores non-caught calls such as fscanf instead of\n"
"  -i               aborting. With -i, fscanf etc. will not transcrypt but\n"
"                   will work.\n"
" --debug, -d       Debugging mode: fe won't transcrypt anything, but pass\n"
"                   through all intercepted libc functions and generate\n"
"                   verbose messages. Implies -v and doesn't need a key.\n"
" --key KEY         Initializes the crypto functions with the stated key.\n"
"  -k KEY           When this flag is absent, the FE_KEY environment variable\n"
"                   is used. When neither -k is given nor FE_KEY is present,\n"
"                   then the key is read from stdin.\n"
" --target FILE     Marks the file as transcryption target in a spawned\n"
"  -t FILE          command. Default is to transcrypt all files within the\n"
"                   arguments. Flag is repeatable to specify more targets.\n"
" --file FILE       Transcrypts in-place the stated file. This encrypts or\n"
"  -f FILE          decrypts stand-alone files, without spawning next\n"
"                   commands.\n"
" --version, -V     prints the version ID on stdout and stops\n"
" --algorithm NR    selects algorithm NR for in-place transcrypting a file\n"
"                   Allowed algorithms are 1 up to the first digit of the\n"
"                   version\n"
"\n"
"When CMD ARGS is given, then it is invoked with fe as a layer underneath\n"
"to transcrypt file(s) that the command opens. Use --target FILE to limit\n"
"the handled file.\n"
"\n");

    exit(1);
}
